### ISSUE TITLE
Issues with sending judge emails

### ISSUE THREAD

**Issue by phulsechinmay** [weareasterisk/gavel#3]
Love the Gavel redesign and the other changes, thanks so much for doing this!

I've been trying to test this out for our hackathon by deploying on heroku and am running across an issue where emails aren't being sent to judges. I configured the old version of gavel and this with the same config, and the old one sent out emails while this one didn't.

Manually clicking on the email buttons next to judges isn't sending emails either.

DISABLE_EMAIL is set to false and the EMAIL_FROM, EMAIL_USER and EMAIL_PASSWORD are set correctly. Is there a config I'm missing?

**Comment by mkhatri1** [comment]
Hey! Thanks for using the gavel redesign! I'll start tracking this issue and try resolve is ASAP. Thanks for catching it...

**Comment by mkhatri1** [comment]
Fixed under the latest release. [v2.0.2](https://github.com/weareasterisk/gavel/releases/tag/v2.0.2)
